### ISSUE TITLE
Launch Kolibri hybrid learning to support learners whose learning has been disrupted by COVID

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-ecosystem#2]
The Kolibri Learning Platform supports hybrid learning experiences between home and learning centers (schools/nonformal)

This will address ongoing disruption to education for learners caused by the COVID-19 pandemic, and as schools return to normal operations, allow for initiatives aimed at addressing the homework gap and supporting learners when they are unable to access synchronous instruction.

Key Results:

- Kolibri Learn has a revamped home page which:
    - provides a shorter path to resources
    - supports both class based and non-class based learning pathways
    - gives quick entry points to both assigned content and content discovery
- Kolibri Ecosystem has at least 3 new types of metadata for content that are used for filtering and display
- Kolibri learner experience should have at least 3 of these 6 features:
    - Resource preview
    - Improved mobile responsiveness of the content page
    - Improved user flow of the content page
    - Customizable display of content listing
    - Improved completion criteria
    - Resource bookmarks

Why?

- Support learners whose learning has been disrupted by COVID
- Allow Kolibri to support initiatives addressing the homework gap
- Support learners who do not have access to synchronous instruction
- 4 years of feedback about the learn experience backlogged in clearinghouse
- The Learn experience has not changed fundamentally since 2017 - IT'S TIME!

**Comment by jtamiace** [comment]
Figma file:
https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning

Access different pages for this project via the menu, which looks different if you're signed in or not
![Screen Shot 2021-04-25 at 5.05.33 PM.png](https://images.zenhubusercontent.com/6047f63852483ffd3d7d34a1/abbed4c3-a776-490a-b68e-4df030beb5ae)


Individual Figma pages specific to each sub-epic will be added soon

**Comment by jtamiace** [comment]
To view how different components lie on KGrid, use the toggle in the menu at the top right![Screen Shot 2021-04-27 at 4.41.20 PM.png](https://images.zenhubusercontent.com/6047f63852483ffd3d7d34a1/d7597c3e-63c7-4bb4-9bfa-d71e3bbec205)
