### ISSUE TITLE
Past Papers Project: Independent practice quizzes for learners

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri-ecosystem#26]
### Summary
Independent practice quizzes, (as we will refer to them here, but aka past papers and practice quizzes) are pre-loaded quizzes that have been imported to Kolibri using content-integration scripts or via Studio.

In Kolibri:
- **Device admin** can import and export channel quizzes
- **Coaches** will be able to assign channel quizzes to their learners as quizzes and in lessons, and view reports
- **Learners** can then access and search for the channel quizzes in channel topics or see them assigned in their classes, as well as view their own reports and retry quizzes

### Dev Deliverables
1. WHL file installer with past papers functionality (possibly contained in beta release for Kolibri 0.16)
2. Documentation of the new past papers functionality for the Kolibri Learning Platform
3. Separate ricecooker class for channel-based quizzes.

### Resources
- [Overview of project - slides](https://docs.google.com/presentation/d/1JGTqYU_syPwtScGqI8xY3c37ImCf9Bo4Ma_2kfWpn9Q/edit#slide=id.gf323b82ee0_0_990)
- [Designs - Figma file](https://www.figma.com/file/TfaSTT9gs6fPKhGdNUjffU/Channel-quizzes?node-id=0%3A1)
- [Gherkin stories - Notion](https://www.notion.so/Gherkin-stories-70b4f58a3f9f447399dffe14512d9eed)
- [Strings - Ditto](https://beta.dittowords.com/doc/6094429123e78e01177aec02)
- [2020 designs for the feature - slides](https://docs.google.com/presentation/d/1L86BdAF72fWQ8-igUE6V7sjEqYHhYXMVmPJvbfBkAaE/edit#slide=id.p)
- [2021 designs for retry behavior and reports - slides](https://www.notion.so/learningequality/Past-papers-aka-channel-based-practice-quizzes-tech-spec-54c87bb85d8d47678ce5714bb9e2c05d#022069e501d44106b949d98e36b1cf5a)
- [Tech spec in detail - Notion](https://www.notion.so/learningequality/Past-papers-aka-channel-based-practice-quizzes-tech-spec-54c87bb85d8d47678ce5714bb9e2c05d)

**Comment by rtibbles** [comment]
All issues completed!
