### ISSUE TITLE
🏠 Create a new Learn home page

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-ecosystem#6]
Objective: Learners in the Learning Platform have a home page that provides quick entrance to learning pathways

- A single home page for Learn that supports both class based and non-class based learning pathways
- Quick entry points to both assigned content and content discovery
- 'Continue learning' scoped to assignments in classes

**Comment by riddhiavlani** [comment]
Home page design 
https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=1788%3A6234

**Comment by rtibbles** [comment]
Complete, closing!
