### ISSUE TITLE
Implement categorical and primary metadata search

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-ecosystem#7]
Objective: Kolibri and Kolibri Studio users are able to use categories and other metadata filters to quickly hone in on resources that are most relevant to their needs

- Kolibri Studio users can efficiently update tags and metadata for new and existing resources
- The Kolibri ecosystem supports new metadata:
    - Estimated time for resource completion
    - User facing learning activity categorization
    - Hierarchical tagsonomies like 'Subject'
- Browse and search for resources in Kolibri and Kolibri Studio using categories and metadata as primary filtering mechanisms

**Comment by jtamiace** [comment]
Specs for the learning platform:
https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=9%3A2
